#!/bin/bash

VENDOR=$(glxinfo | grep "OpenGL vendor")

if [[ $VENDOR == *"NVIDIA"* ]]; then
    export __GL_THREADED_OPTIMIZATIONS=1
fi

export QTWEBENGINEPROCESS_PATH=$SNAP/opt/qt515/libexec/QtWebEngineProcess

#Path to Vulkan ICD files depending on CPU architecture
case $SNAP_ARCH in
  amd64)
    ARCH="x86_64"
    export VK_ICD_FILENAMES=/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.$ARCH.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.$ARCH.json
    ;;
  arm64)
    ARCH="aarch64"
    export VK_ICD_FILENAMES=/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.$ARCH.json
    ;;
  i386)
    ARCH="i686"
    export VK_ICD_FILENAMES=/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.$ARCH.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.$ARCH.json
    ;;
  armhf)
    ARCH="arm"
    export VK_ICD_FILENAMES=/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.$ARCH.json
    ;;
esac

# Workaround for impish Nvidia discussed here:
#  - https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH#$SNAP_LIBRARY_PATH:}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${SNAP_LIBRARY_PATH}"

# Add additional path for KDEPlasmaPlatformTheme.so, until I can figure out how to move this to be with the other Qt plugins
export QT_PLUGIN_PATH=$QT_PLUGIN_PATH:$SNAP/kf5/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET/plugins

# Add KF5 libexec directory containing kioslave5 for KDE file picker when not using portals
export PATH=$PATH:$KF5_LIBEXEC_DIR

exec "${@}"
