#!/bin/bash

VENDOR=$(glxinfo | grep "OpenGL vendor")

if [[ $VENDOR == *"NVIDIA"* ]]; then
    export __GL_THREADED_OPTIMIZATIONS=1
fi

export QTWEBENGINEPROCESS_PATH=$SNAP/opt/qt515/libexec/QtWebEngineProcess

exec "${@}"
