name: yuzu # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: yuzu is an experimental open-source emulator for the Nintendo Switch # 79 char long summary
description: |
  Nintendo Switch Emulator. yuzu is an experimental open-source emulator for the Nintendo Switch from the creators of Citra. 
  It is written in C++ with portability in mind, with builds actively maintained for Windows and Linux.
license: GPL-2.0
icon: snap/gui/yuzu.svg
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  yuzu:
    source: https://github.com/yuzu-emu/yuzu-mainline.git
    plugin: nil
    # cmake-parameters: ["-DCMAKE_INSTALL_PREFIX="]
    override-build: |
      pip3 install conan
      mkdir build && cd build
      export DESTDIR=$SNAPCRAFT_PART_INSTALL
      cmake .. -GNinja
      ninja
      ninja install
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - python3-pip
      - sqlite3
      - libsqlite3-dev
      - libsdl2-dev 
      - python3-setuptools
      - qtbase5-dev 
      - libqt5opengl5-dev 
      - libqt5svg5
      - qtwebengine5-dev 
      - qtbase5-private-dev 
      - libvulkan-dev
      - python
      - libboost-dev
      - libboost-context-dev
      - libfmt-dev
      - libzip-dev
      - liblz4-dev 
      - libmbedtls-dev
      - libssl-dev
      - libopus-dev
      - zlib1g-dev
      - libzstd-dev
    stage-packages:
      - libsdl2-2.0-0
      - libxi6
      - libxinerama1
      - libxrandr2
      - qt5-gtk-platformtheme
    stage:
      - -lib/x86_64-linux-gnu/libdbus-1.so.3.19.11
      - -usr/share/doc/libdbus-1-3/changelog.Debian.gz
    after:
      - desktop-qt5
  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgtk2.0-0
    - libgdk-pixbuf2.0-0
    - libqt5svg5
    - libgpm2
    - freeglut3
    - libslang2
    - libsdl2-2.0-0
    - mesa-utils
    - libgl1-mesa-glx
    - libopus0
    - try:
      - appmenu-qt5
    - locales-all
    - xdg-user-dirs
    - libzip5
    - libpulse-dev
    - pulseaudio
    - libpulse0

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

  
apps:
  yuzu:
    command: bin/desktop-launch $SNAP/usr/local/bin/yuzu
    environment:
      "QT_QPA_PLATFORM_PLUGIN_PATH": "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins"
      "FONTCONFIG_SYSROOT": $SNAP
      "FONTCONFIG_PATH": $SNAP/etc/fonts/config.d
      "FONTCONFIG_FILE": $SNAP/etc/fonts/fonts.conf
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    plugs:
      - desktop
      - x11
      - wayland
      - pulseaudio
      - opengl
      - joystick
      - unity7
      - unity8
      - mir
      - network
      - home
      - removable-media
  