name: yuzu # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: yuzu is an experimental open-source emulator for the Nintendo Switch # 79 char long summary
description: |
  Nintendo Switch Emulator. yuzu is an experimental open-source emulator for the Nintendo Switch from the creators of Citra. 
  It is written in C++ with portability in mind, with builds actively maintained for Windows and Linux.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  yuzu:
    source: https://github.com/yuzu-emu/yuzu-mainline.git
    # See 'snapcraft plugins'
    plugin: cmake
    build-snaps:
      - cmake
    override-build: |
      pip3 install conan
      cmake ../src \
        -GNinja
      ninja
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - python3-pip
      - sqlite3
      - libsqlite3-dev
      - libsdl2-dev 
      - qtbase5-dev 
      - libqt5opengl5-dev 
      - qtwebengine5-dev 
      - qtbase5-private-dev 
      - python
      - libboost-dev
      - libboost-context-dev
      - libfmt-dev
      - libzip-dev
      - liblz4-dev 
      - libmbedtls-dev
      - libssl-dev
      - libopus-dev
      - zlib1g-dev
      - libzstd-dev

    

apps:
  yuzu:
    command: yuzu
