name: yuzu # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0-289' # just for humans, typically '1.2+git' or '1.3.2'
summary: yuzu is an experimental open-source emulator for the Nintendo Switch # 79 char long summary
description: |
  Nintendo Switch Emulator. yuzu is an experimental open-source emulator for the Nintendo Switch from the creators of Citra. 
  It is written in C++ with portability in mind, with builds actively maintained for Windows and Linux.
license: GPL-2.0
icon: snap/gui/yuzu.svg
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  yuzu:
    source: https://github.com/yuzu-emu/yuzu-mainline.git
    source-tag: mainline-$SNAPCRAFT_PROJECT_VERSION
    plugin: nil
    override-build: |
      pip3 install conan
      mkdir build && cd build
      export DESTDIR=$SNAPCRAFT_PART_INSTALL
      cmake .. -GNinja
      ninja
      ninja install
      sed -i 's|Icon=yuzu|Icon=/usr/local/share/icons/hicolor/scalable/apps/yuzu.svg|' $SNAPCRAFT_PART_INSTALL/usr/local/share/applications/yuzu.desktop
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - python3-pip
      - sqlite3
      - libsqlite3-dev
      - libsdl2-dev 
      - python3-setuptools
      - qtbase5-dev 
      - libqt5opengl5-dev 
      - libqt5svg5
      - qtwebengine5-dev 
      - qtbase5-private-dev 
      - libvulkan-dev
      - python
      - libboost-dev
      - libboost-context-dev
      - libfmt-dev
      - libzip-dev
      - liblz4-dev 
      - libmbedtls-dev
      - libssl-dev
      - libopus-dev
      - zlib1g-dev
      - libzstd-dev
    stage-packages:
      - libsdl2-2.0-0
      - libxi6
      - libxinerama1
      - libxrandr2
      - qt5-gtk-platformtheme
      - libcanberra-gtk-module
    stage:
      - -lib/x86_64-linux-gnu/libdbus-1.so.3.19.11
      - -usr/share/doc/libdbus-1-3/changelog.Debian.gz
    after:
      - desktop-qt5
  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgtk2.0-0
    - libgdk-pixbuf2.0-0
    - libqt5svg5
    - libgpm2
    - freeglut3
    - libslang2
    - libsdl2-2.0-0
    - mesa-utils
    - libgl1-mesa-glx
    - libopus0
    - try:
      - appmenu-qt5
    - locales-all
    - xdg-user-dirs
    - libzip5
    - libpulse-dev
    - libpulse0
  plasma-integration:
    plugin: nil
    stage-packages:
      - kio
      - breeze-icon-theme
      - kde-style-breeze
      - libkf5iconthemes5
      - libkf5configgui5
      - libkf5configcore5
      - libkf5completion5
      - libkf5notifications5
      - libkf5coreaddons5 
      - libqt5widgets5
      - libqt5gui5
      - libkf5xmlgui5
      - libqt5x11extras5
      - libqt5core5a
      - libkf5widgetsaddons5
      - libxcb1
      - libkf5kiocore5 
      - libkf5kiofilewidgets5 
      - libkf5kiowidgets5
      - plasma-integration
    override-prime: |
      snapcraftctl prime
      # figure out how to use an env variable to point to $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5/kioslave5 to avoid duplicating binary
      cp $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5/kioslave5 $SNAPCRAFT_PRIME/usr/local/bin

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

# slots:
#   dbus-yuzu:
#       interface: dbus
#       name: org.yuzu.yuzu
#       bus: session

apps:
  yuzu:
    command: bin/desktop-launch $SNAP/usr/local/bin/yuzu
    desktop: usr/local/share/applications/yuzu.desktop
    environment:
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    # slots:
    #   - dbus-yuzu    
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - pulseaudio
      - opengl
      - joystick
      - unity7
      - unity8
      - mir
      - network
      - home
      - removable-media
      - gsettings
      - udisks2
      - hardware-observe
      - block-devices
      - mount-observe
      - upower-observe
      # - system-files

