name: yuzu
base: core20
version: '704'
summary: Nintendo Switch Emulator
description: |
  yuzu is an experimental open-source emulator for the Nintendo Switch from the creators of Citra. 
  It is written in C++ with portability in mind, with builds actively maintained for Windows and Linux.

  yuzu only emulates a subset of Switch hardware and therefore most commercial games do not run at full speed or are not fully functional.

  Usage: Launch yuzu from your desktop app-launcher or run the command *`yuzu`* from the terminal. If you have already installed yuzu by 
  alternative means, use the command *`snap run yuzu`*. To launch *`yuzu-cmd`*, run the command *`snap run yuzu.yuzu-cmd`*.
  Enable the relevant permissions. Yuzu folder location: *`$HOME/snap/yuzu/common/.local/share/yuzu`*

  This snap is not necessarily endorsed or officially maintained by the upstream developers.

  Upstream Project: https://yuzu-emu.org/
  snapcraft.yaml Build Definition: https://github.com/Nightmayr/yuzu-snap/blob/master/snap/snapcraft.yaml

  Donate to yuzu: https://yuzu-emu.org/donate
license: GPL-2.0
icon: snap/gui/yuzu.png
grade: stable
confinement: strict
architectures:
  - build-on: amd64
# package-repositories:
  # - type: apt
  #   ppa: cybermax-dexter/sdl2-backport
  # - type: apt
  #   ppa: beineri/opt-qt-5.15.2-focal
parts:
  yuzu:
    source: https://github.com/yuzu-emu/yuzu-mainline.git
    source-tag: mainline-0-$SNAPCRAFT_PROJECT_VERSION
    plugin: cmake
    cmake-parameters: 
    - -DCMAKE_BUILD_TYPE=Release
    - -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON
    - -DUSE_DISCORD_PRESENCE=ON
    - -DENABLE_QT_TRANSLATION=ON
    - -DYUZU_USE_QT_WEB_ENGINE=ON
    - -DYUZU_ENABLE_COMPATIBILITY_REPORTING=${ENABLE_COMPATIBILITY_REPORTING:-"OFF"}
    - -DDISPLAY_VERSION=$SNAPCRAFT_PROJECT_VERSION
    - -DBUILD_TAG=mainline-$SNAPCRAFT_PROJECT_VERSION"
    - -DBUILD_REPOSITORY=yuzu-emu/yuzu-mainline"
    build-environment:
      - TITLEBARFORMATIDLE: "yuzu {}"
      - TITLEBARFORMATRUNNING: "yuzu {} | {}"
      - LDFLAG: "-L$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
    cmake-generator: Ninja
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/nodirtyversion.patch
    override-build: |
      if [ ! -f /usr/bin/lsb_release ]; then
        apt install -y lsb-release
      fi
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
      pip3 install conan
      snapcraftctl build
      sed -i 's|Icon=yuzu|Icon=/usr/local/share/icons/hicolor/scalable/apps/yuzu.svg|' $SNAPCRAFT_PART_INSTALL/usr/local/share/applications/yuzu.desktop
    build-packages:
    - cmake
    - ninja-build
    - build-essential
    - gcc-10
    - g++-10
    - python3-pip
    - sqlite3
    - libsqlite3-dev
    - python3-setuptools
    # - qtbase5-dev 
    # - qtwebengine5-dev 
    # - qtbase5-private-dev 
    # - libqt5opengl5-dev 
    # - libqt5svg5
    # - qttools5-dev
    # - qttools5-dev-tools
    - libvulkan-dev
    - python
    - libfmt-dev
    - libzip-dev
    - liblz4-dev 
    - libmbedtls-dev
    - libssl-dev
    - libopus-dev
    - zlib1g-dev
    - libzstd-dev
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libswscale-dev
    - autotools-dev
    - automake
    - autoconf
    - libtool
    - libpulse-dev
    - libasound2
    - libhidapi-dev
    # - glslang-tools
    # - qt515base
    # - qt515declarative
    # - qt515xmlpatterns
    # - qt515wayland
    # - qt515svg
    # - qt515tools
    # - qt515webengine
    - libudev-dev
    - libx11-dev
    - libxext-dev
    - libgl-dev
    stage-packages:
    # - libsdl2-2.0-0
    - libxi6
    - libxinerama1
    - libxrandr2
    - qt5-gtk-platformtheme
    - libvulkan1
    - mesa-vulkan-drivers
    - vulkan-utils
    - libzip5
    - libpulse0
    - libgl1-mesa-glx
    - libopus0
    - mesa-utils
    - xdg-utils
    # - libqt5webengine5
    # - libqt5webenginewidgets5
    - libswscale5
    - libavformat58
    - libavcodec58
    - libavutil56
    - libhidapi-libusb0
    - libhidapi-hidraw0
    - libasound2
    stage:
    - -lib/x86_64-linux-gnu/libdbus-1.so.3.19.11
    - -usr/share/doc/libdbus-1-3/changelog.Debian.gz
    - -lib/x86_64-linux-gnu/libz.so.1.2.11
    - -usr/share/doc
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Core.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5DBus.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5EglFSDeviceIntegration.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Gui.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Network.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5PrintSupport.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Svg.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Widgets.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5XcbQpa.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Xml.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5EglFsKmsSupport.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5
    after:
    - patches
    - qt5
    - desktop-qt5
    - glslangvalidator
  glslangvalidator:
    plugin: nil
    source: https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-linux-Release.zip
    override-build: |
      cp -r $SNAPCRAFT_PART_BUILD/* /usr
    prime:
    - -*

  desktop-qt5:
    source: https://github.com/desktop-app/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - xdg-user-dirs
      - libgtk2.0-0
    override-prime: |
      snapcraftctl prime
      sed -i 's|XDG_DATA_HOME=$SNAP_USER_DATA|XDG_DATA_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
      sed -i 's|XDG_CONFIG_HOME=$SNAP_USER_DATA|XDG_CONFIG_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
    stage:
      - -usr/share/doc
    after:
      - qt5

  qt5:
    plugin: nil
    build-packages:
      - libdbus-1-dev
      - libegl-dev
      - libfontconfig1-dev
      - libfreetype-dev
      - libgl-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libharfbuzz-dev
      - libicu-dev
      - libpcre2-dev
      - libpng-dev
      - libssl-dev
      - libwayland-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-render-util0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-util-dev
      - libxcb-xfixes0-dev
      - libxcb-xinerama0-dev
      - libxcb-xinput-dev
      - libxcb-xkb-dev
      - libxcursor-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - zlib1g-dev
      # webengine deps
      - libxcomposite-dev
      - libxdamage-dev
      - libxrandr-dev
      - libxtst-dev
      - libxss-dev
      - libevent-dev
      - libcap-dev
      - libpulse-dev
      - libudev-dev
      - libpci-dev
      - libnss3-dev
      - libasound2-dev
      - libegl1-mesa-dev
      - gperf
      - bison
      - nodejs
      - libdrm-dev
      - flex
      - libxcb-dri3-dev
      # optional webengine deps
      - libsrtp2-dev
      - libjsoncpp-dev
      - libopus-dev
      - libminizip-dev
      - libavutil-dev
      - libavformat-dev
      - libavcodec-dev
      - libvpx-dev
      - libsnappy-dev
      - libre2-dev
      - libprotobuf-dev
      - protobuf-compiler
    stage-packages:
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libgl1
      - libglib2.0-0
      - libgtk-3-0
      - libharfbuzz0b
      - libicu66
      - libpcre2-16-0
      - libpng16-16
      - libssl1.1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - zlib1g
      - libasound2
      - libevent-2.1-7
      - libice6
      - libjpeg-turbo8
      - libminizip1
      - libnspr4
      - libnss3
      - libopus0
      - libre2-5
      - libsm6
      - libsnappy1v5
      - libvpx6
      - libxss1
    override-pull: |
      git clone -b v5.15.2 --depth=1 git://code.qt.io/qt/qt5.git .
      perl init-repository --module-subset=qtbase,qtwayland,qtimageformats,qtsvg,qttools,qtwebengine,qtdeclarative
      git submodule update qtbase qtwayland qtimageformats qtsvg qtwebengine qttools qtdeclarative

      cd qtbase
      git apply $SNAPCRAFT_STAGE/qtbase-ordonly.patch
    override-build: |
      ./configure \
        -prefix /usr \
        -bindir /usr/lib/qt5/bin \
        -libdir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET \
        -docdir /usr/share/qt5/doc \
        -headerdir /usr/include/$SNAPCRAFT_ARCH_TRIPLET/qt5 \
        -datadir /usr/share/qt5 \
        -archdatadir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5 \
        -plugindir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins \
        -importdir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/imports \
        -translationdir /usr/share/qt5/translations \
        -hostdatadir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5 \
        -sysconfdir /etc/xdg \
        -examplesdir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/examples \
        -release \
        -opensource \
        -confirm-license \
        -nomake examples \
        -nomake tests \
        -I $SNAPCRAFT_STAGE/usr/include \
        -L $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      echo $?
      make INSTALL_ROOT="$SNAPCRAFT_PART_INSTALL" install
      echo $?
    stage:
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2
    prime:
      - -./usr/include
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/bin
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/mkspecs
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/examples
      # Allow tdesktop's custom try-portal-and-fallback logic to work
      # - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/platformthemes/libqxdgdesktopportal.so
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.a
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.la
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.prl
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.so
      - -./usr/lib/qt5
      - -./usr/share
    after:
      - patches

  plasma-integration:
    plugin: nil
    stage-packages:
    - breeze-icon-theme
    - kde-style-breeze
    - plasma-integration
    stage:
    - -usr/share/doc
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Core.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5DBus.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5EglFSDeviceIntegration.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Gui.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Network.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5PrintSupport.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Svg.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Widgets.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5XcbQpa.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Xml.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5EglFsKmsSupport.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Qml.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Quick.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5QuickWidgets.so.5
    - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5
  patches:
    plugin: dump
    source: snap/local/patches
    source-type: local
    prime:
      - -*
  launchers:
    plugin: dump
    source: snap/local/launchers
    source-type: local
    organize:
      '*': bin/
  glib2:
    plugin: nil
    stage-packages:
      - libglib2.0-0
    stage:
    - -usr/share/doc

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/share/vulkan:
    symlink: $SNAP/usr/share/vulkan
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so
  /usr/share/qt5:
    symlink: $SNAP/usr/share/qt5

apps:
  yuzu:
    command: usr/local/bin/yuzu
    command-chain:
    - "bin/yuzu-launch"
    - "bin/desktop-launch"
    - "bin/vulkan-icd-files"
    desktop: usr/local/share/applications/yuzu.desktop
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      KDE_FORK_SLAVES: 1
      DISABLE_WAYLAND: 1
      PATH: "$PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5"
    plugs:
    - desktop
    - desktop-legacy
    - x11
    - wayland
    - audio-playback
    - opengl
    - joystick
    - unity7
    - network
    - network-bind
    - home
    - removable-media
    - gsettings
    - hardware-observe
    - mount-observe
    - bluez
    - browser-support
    - screen-inhibit-control
    - raw-usb
  yuzu-cmd:
    command: usr/local/bin/yuzu-cmd
    command-chain:
    - "bin/vulkan-icd-files"
    - "bin/yuzu-launch"
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1 
    plugs:
    - x11
    - wayland
    - audio-playback
    - opengl
    - joystick
    - network
    - network-bind
    - home
    - removable-media
    - hardware-observe
    - mount-observe
    - bluez
    - browser-support
    - screen-inhibit-control
    - raw-usb

