name: yuzu # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: yuzu is an experimental open-source emulator for the Nintendo Switch # 79 char long summary
description: |
  Nintendo Switch Emulator. yuzu is an experimental open-source emulator for the Nintendo Switch from the creators of Citra. 
  It is written in C++ with portability in mind, with builds actively maintained for Windows and Linux.
license: GPL-2.0
icon: snap/gui/yuzu.svg
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  # qt: # this 'part' will probably not be needed once base core20 is available
  #   source: https://code.qt.io/qt/qt5.git
  #   source-branch: "5.12"
  #   plugin: make
  #   override-build: |
  #     ./configure -opensource -nomake examples -nomake tests
  #     export DESTDIR="/root/parts/qt/install"
  #     # make -j$(nproc)
  #     make -j$(($(nproc)-2))
  #     make install
  #   build-packages:
  #     - libvulkan-dev
  #   # stage:
  #   #   - -*
  qt5:
    plugin: nil
    stage-snaps:
      - kde-frameworks-5-core18
      - kde-frameworks-5-core18-sdk
    stage-packages:
      - libgpm2
      - freeglut3
      - libslang2
      - libsdl2-2.0-0
      - mesa-utils
      - libgl1-mesa-glx
    filesets:
      library-shared:
      - '**/lib/**/*.so*'
    stage:
      - -bin/bunzip2
      - -bin/bzcat
      - -bin/bzip2
      - -bin/bzip2recover
      - etc
      - $library-shared
    prime:
      - $library-shared
      - etc
  yuzu:
    source: https://github.com/yuzu-emu/yuzu-mainline.git
    plugin: cmake
    build-snaps:
      - cmake
      - kde-frameworks-5-core18
      - kde-frameworks-5-core18-sdk
    override-build: |
      pip3 install conan
      snapcraftctl build
      cp -R ../src/dist ../install
      # cmake -DCMAKE_PREFIX_PATH=/usr/local/Qt-5.12.8/lib/cmake ../src \
      # cmake ../src \
      #   -GNinja
      # ninja
      # DESTDIR=../install ninja install
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - python3-pip
      - sqlite3
      - libsqlite3-dev
      - libsdl2-dev 
      # - qtbase5-dev 
      # - libqt5opengl5-dev 
      # - qtwebengine5-dev 
      # - qtbase5-private-dev 
      # - libvulkan-dev
      - python
      - libboost-dev
      - libboost-context-dev
      - libfmt-dev
      - libzip-dev
      - liblz4-dev 
      - libmbedtls-dev
      - libssl-dev
      - libopus-dev
      - zlib1g-dev
      - libzstd-dev
    stage-packages:
      - libsdl2-2.0-0
      - libxi6
      - libxinerama1
      - libxrandr2
      - git
      # - libsdl2-dev
    # filesets:
    #   library-shared:
    #   - '**/lib/**/libSDL2-2.0.so.0'
    #   # - '**/lib/**/'
    stage:
      - share
      - bin
      - dist
      - lib
      - -lib/x86_64-linux-gnu/libcom_err.so.2.1
      # - etc
      # - '**/lib/**/libSDL2-2.0.so.0'
      # - $library-shared
    after:
      - qt5
  # desktop-qt5:
  #   build-packages:
  #   - build-essential
  #   - qtbase5-dev
  #   - dpkg-dev
  #   make-parameters:
  #   - FLAVOR=qt5
  #   plugin: make
  #   source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
  #   source-subdir: qt
  #   stage-packages:
  #   - libxkbcommon0
  #   - ttf-ubuntu-font-family
  #   - dmz-cursor-theme
  #   - light-themes
  #   - adwaita-icon-theme
  #   - gnome-themes-standard
  #   - shared-mime-info
  #   - libqt5gui5
  #   - libgdk-pixbuf2.0-0
  #   - libqt5svg5
  #   - try:
  #     - appmenu-qt5
  #   - locales-all
  #   - xdg-user-dirs

    

apps:
  yuzu:
    # command: ../parts/yuzu/build/bin/yuzu
    command: bin/yuzu
    environment:
      "QT_QPA_PLATFORM_PLUGIN_PATH": "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins"
      "XDG_RUNTIME_DIR": "/run/user/1000"
      "FONTCONFIG_SYSROOT": $SNAP
      "FONTCONFIG_PATH": $SNAP/etc/fonts/config.d
      "FONTCONFIG_FILE": $SNAP/etc/fonts/fonts.conf
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
    plugs:
      - desktop
      - x11
      - wayland
      - pulseaudio
      - opengl
      - joystick
      - unity7
      - unity8
      - mir
      - network
      - home
  