name: Build-Snap-Edge

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#       with:
#         token: ${{ secrets.PAT }}
    - uses: snapcore/action-build@v1
      with:
       snapcraft-args: --enable-experimental-package-repositories
      id: snapcraft
    - name: Testing snap
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        snap run yuzu.yuzu-cmd --version
    - uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
