name: Build-Snap

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v2
    # - name: Setup workflow environment
      # run: |
      #   sudo apt install jq
      #   alias snapcraft="snapcraft --enable-experimental-package-repositories"
    - name: Check latest version
      run: ./.github/scripts/version.sh
    - name: Already latest version - cancelling
      uses: andymckay/cancel-action@0.2
    - uses: snapcore/action-build@v1
    - name: Test snap
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        snap run yuzu.yuzu-cmd --version
        # echo ::set-output name=exitcode::$(snap run yuzu.yuzu-cmd --version)
        # add conditional logic for exit code not equal to 0
    - name: Update yaml version
      run: |
        git config --global user.name 'Nightmayr'
        git config --global user.email 'umayr23@gmail.com'
        git commit -am "Updating version [skip ci]"
        git push

