name: Build-Snap

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Check latest version
      run: |
        ./.github/scripts/version.sh
        echo ::set-env name=BUILD::$(cat build)
        echo ::set-env name=LATEST_VERSION::$(cat latest)
        echo ::set-env name=CURRENT_VERSION::$(cat current)
      id: version-check
    - name: Already latest version - cancelling
      if: env.BUILD == 'false'
      uses: andymckay/cancel-action@0.2
    - name: Update snapcraft.yaml version
      run: | 
        sed -i "s/version: '${{ env.CURRENT_VERSION }}'/version: '${{ env.LATEST_VERSION }}'/g" snap/snapcraft.yaml
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Testing snap
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        snap run yuzu.yuzu-cmd --version
    - name: Committing updated snapcraft.yaml #Move to be after publish once pushing confirmed to work
      run: |
        git config --global user.name 'Buildbot'
        git config --global user.email 'umayr23@gmail.com'
        git commit -am "Updating version [ci-skip]"
        git push origin master
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ step.snapcraft.outputs.snap }}
        release: stable

